### ISSUE TITLE
Problem with `bootstrap3_datetime`

### ISSUE THREAD

**Issue by yn-coder** [postpdm/ich_bau#9]
Subtask for #2 
Problem with `bootstrap3_datetime` - package is outdated and uncompatible with django 1.11

https://github.com/nkunihiko/django-bootstrap3-datetimepicker/pull/67 is not merged

**Comment by yn-coder** [comment]
`pip install git+https://github.com/jsanchezislas/django-bootstrap3-datetimepicker.git@build_attrs` doesn't help. Py working fine with Django 1.11, but js is raise an errors `(index):34 Uncaught TypeError: jQuery(...).datetimepicker is not a function` in browser console. JS in package is outdated too

**Comment by yn-coder** [comment]
Replace with http://django-crispy-forms.readthedocs.io/en/latest/ ?

**Comment by yn-coder** [comment]
`#django-bootstrap3-datetimepicker-2==2.4.2
git+git://github.com/blag/django-bootstrap3-datetimepicker.git@f8a78b231b75c331c143d5461456f663827a8af6`

**Comment by yn-coder** [comment]
Old https://github.com/nkunihiko/django-bootstrap3-datetimepicker is abandoned. Then I take https://github.com/jsanchezislas/django-bootstrap3-datetimepicker and see it's conflicted with pnax jquery loading

**Comment by yn-coder** [comment]
Travis is ok. Coverage is down
